import Link from "next/link";
import { VisitorShell } from "@/components/visitor/visitor-shell";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Icon } from "@/components/ui/icons";
import { Input } from "@/components/ui/input";

export default function HomePage() {
  return <VisitorShell><div className="visitor-stack"><section className="visitor-hero"><Icon className="visitor-hero__mark" name="tree" size={132} strokeWidth={1} /><div className="visitor-hero__content"><p className="visitor-kicker">Forest Lake Memorial Park</p><h1>A peaceful way to find a resting place.</h1><p>Use GraveNav to locate a loved one with dignity, clarity, and confidence as you walk through the grounds.</p></div></section><Card id="visitor-search"><CardHeader><CardTitle className="card-title-with-icon"><Icon className="text-green" name="search" size={22} />Find a gravesite</CardTitle></CardHeader><CardContent><form action="/results" className="visitor-search-form" method="get"><Input label="Deceased name" name="query" placeholder="Enter first or last name" icon="userSearch" /><button className="filter-link" type="button"><Icon name="sliders" size={17} />Advanced filters <span>(section, block, date)</span></button><Button className="button--full" icon="search" size="lg" type="submit">Search gravesite</Button></form></CardContent></Card><Alert icon="info" title="First-time visitor?" variant="info">Use search to find a specific grave. Once located, the map can provide walking directions from your current location within the park.<Link className="alert-link" href="/map">View park map <Icon className="inline-icon" name="arrowUpRight" size={15} /></Link></Alert><section className="visitor-info-card"><div><p className="visitor-kicker">On the way</p><h2>Keep this tool close</h2><p>The visitor layout keeps search, map, and helpful context within easy reach on a phone.</p></div><span className="visitor-info-card__icon"><Icon name="walk" size={21} /></span></section><footer className="visitor-footer"><p>© 2024 Forest Lake Memorial Park. All rights reserved.</p><Link href="/">Privacy notice</Link></footer></div></VisitorShell>;
}
