-- GraveNav initial schema migration.
--
-- This migration is intentionally local-first and contains no seed data. GPS and
-- image-map coordinates remain nullable until they are collected. Verification
-- describes data quality and is not a public visibility gate.

create schema if not exists extensions;
create extension if not exists postgis with schema extensions;

set search_path = public, extensions;

create table public.site (
    site_id bigint generated by default as identity primary key,
    site_name text not null,
    address text not null,
    boundary_geom extensions.geography(Polygon, 4326),
    geo_transform_json jsonb,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table public.area (
    area_id bigint generated by default as identity primary key,
    site_id bigint not null references public.site(site_id) on delete restrict,
    area_code varchar(100) not null,
    area_name text not null,
    area_category text not null,
    boundary_geom extensions.geography(Polygon, 4326),
    constraint area_site_code_key unique (site_id, area_code)
);

create table public.sector (
    sector_id bigint generated by default as identity primary key,
    area_id bigint not null references public.area(area_id) on delete restrict,
    sector_code text not null,
    sector_name text,
    constraint sector_area_code_key unique (area_id, sector_code)
);

create table public.block (
    block_id bigint generated by default as identity primary key,
    sector_id bigint not null references public.sector(sector_id) on delete restrict,
    block_number smallint not null,
    block_name text,
    pricing_tier text,
    constraint block_pricing_tier_check
        check (pricing_tier is null or pricing_tier in ('STD', 'PRM', 'SPR')),
    constraint block_number_positive_check check (block_number > 0),
    constraint block_sector_number_key unique (sector_id, block_number)
);

create table public.lot_owner (
    lot_owner_id bigint generated by default as identity primary key,
    first_name text not null,
    middle_name text,
    last_name text not null,
    suffix text,
    aliases text,
    address text not null,
    representative_name text,
    representative_contact text,
    representative_relation text
);

create table public.lot (
    lot_id bigint generated by default as identity primary key,
    block_id bigint not null references public.block(block_id) on delete restrict,
    lot_owner_id bigint references public.lot_owner(lot_owner_id) on delete set null,
    lot_code text not null,
    legacy_location_code text not null,
    legacy_pa_number text,
    status text not null default 'AVAILABLE',
    length_m double precision,
    width_m double precision,
    px_loc_x integer,
    px_loc_y integer,
    location_geom extensions.geography(Point, 4326),
    coordinate_accuracy_m double precision,
    coordinate_status text not null default 'pending',
    coordinate_verified boolean not null default false,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint lot_block_code_key unique (block_id, lot_code),
    constraint lot_status_check
        check (status in ('AVAILABLE', 'BOOKED', 'HOLD')),
    constraint lot_coordinate_status_check
        check (coordinate_status in ('pending', 'verified', 'rejected')),
    constraint lot_coordinate_consistency_check
        check (not coordinate_verified or coordinate_status = 'verified'),
    constraint lot_dimensions_check
        check ((length_m is null or length_m > 0) and (width_m is null or width_m > 0)),
    constraint lot_image_coordinates_check
        check ((px_loc_x is null or px_loc_x >= 0) and (px_loc_y is null or px_loc_y >= 0)),
    constraint lot_coordinate_accuracy_check
        check (coordinate_accuracy_m is null or coordinate_accuracy_m >= 0)
);

create table public.deceased (
    deceased_id bigint generated by default as identity primary key,
    display_name text not null,
    birth_date date,
    death_date date,
    public_display boolean not null default false,
    cause_of_death text,
    constraint deceased_date_order_check
        check (birth_date is null or death_date is null or birth_date <= death_date)
);

create table public.role (
    role_id bigint generated by default as identity primary key,
    role_name text not null,
    description text not null,
    constraint role_name_key unique (role_name)
);

create table public.account (
    account_id uuid primary key references auth.users(id) on delete restrict,
    role_id bigint not null references public.role(role_id) on delete restrict,
    username text not null,
    is_active boolean not null default false,
    account_status text not null default 'PENDING',
    created_by uuid references public.account(account_id) on delete set null,
    approved_by uuid references public.account(account_id) on delete set null,
    approved_at timestamptz,
    deactivated_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint account_username_key unique (username),
    constraint account_status_check
        check (account_status in ('PENDING', 'ACTIVE', 'SUSPENDED', 'REVOKED')),
    constraint account_active_consistency_check
        check (is_active = (account_status = 'ACTIVE')),
    constraint account_approval_check
        check (account_status <> 'ACTIVE' or approved_at is not null),
    constraint account_deactivation_check
        check (deactivated_at is null or account_status in ('SUSPENDED', 'REVOKED'))
);

-- These are controlled role definitions, not user or cemetery seed records.
insert into public.role (role_name, description)
values
    ('ADMIN', 'Full administrator access, including controlled account management.'),
    ('MANAGER', 'Operational cemetery management, verification, photo approval, and audit read/export access.')
on conflict (role_name) do nothing;

create table public.burial_record (
    burial_id bigint generated by default as identity primary key,
    deceased_id bigint not null references public.deceased(deceased_id) on delete restrict,
    lot_id bigint not null references public.lot(lot_id) on delete restrict,
    created_by uuid references public.account(account_id) on delete set null,
    updated_by uuid references public.account(account_id) on delete set null,
    interment_order_number text,
    reference_no text,
    interment_date date,
    record_status text not null default 'pending',
    interment_status text not null,
    remains_type text not null,
    exhumation_date date,
    service_provider text,
    record_source text,
    quality_notes text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint burial_record_status_check
        check (record_status in ('active', 'archived', 'pending')),
    constraint burial_interment_status_check
        check (interment_status in ('PERMANENT', 'TEMPORARY')),
    constraint burial_remains_type_check
        check (remains_type in ('FRESH', 'ASH', 'BONE')),
    constraint burial_date_order_check
        check (exhumation_date is null or interment_date is null or interment_date <= exhumation_date)
);

create table public.photo (
    photo_id bigint generated by default as identity primary key,
    burial_id bigint not null references public.burial_record(burial_id) on delete restrict,
    uploaded_by uuid not null references public.account(account_id) on delete restrict,
    reviewed_by uuid references public.account(account_id) on delete set null,
    storage_path text not null,
    file_name text not null,
    caption text,
    captured_at date,
    approval_status text not null default 'pending',
    public_display boolean not null default false,
    created_at timestamptz not null default current_timestamp,
    constraint photo_storage_path_key unique (storage_path),
    constraint photo_approval_status_check
        check (approval_status in ('pending', 'approved', 'rejected'))
);

create table public.map_node (
    node_id bigint generated by default as identity primary key,
    site_id bigint not null references public.site(site_id) on delete restrict,
    node_name text not null,
    node_type text not null,
    px_loc_x integer,
    px_loc_y integer,
    location_geom extensions.geography(Point, 4326),
    constraint map_node_type_check
        check (node_type in ('entrance', 'junction', 'landmark')),
    constraint map_node_image_coordinates_check
        check ((px_loc_x is null or px_loc_x >= 0) and (px_loc_y is null or px_loc_y >= 0))
);

create table public.map_edge (
    edge_id bigint generated by default as identity primary key,
    from_node_id bigint not null references public.map_node(node_id) on delete restrict,
    to_node_id bigint not null references public.map_node(node_id) on delete restrict,
    path_geom extensions.geography(LineString, 4326),
    distance_m double precision,
    edge_type text not null,
    is_restricted boolean not null default false,
    constraint map_edge_distinct_nodes_check check (from_node_id <> to_node_id),
    constraint map_edge_distance_check check (distance_m is null or distance_m >= 0),
    constraint map_edge_type_check
        check (edge_type in ('path', 'road', 'entrance'))
);

create table public.audit_log (
    audit_id bigint generated by default as identity primary key,
    actor_account_id uuid references public.account(account_id) on delete set null,
    action text not null,
    table_name text not null,
    record_id text not null,
    old_values jsonb,
    new_values jsonb,
    ip_address inet,
    created_at timestamptz not null default current_timestamp,
    constraint audit_action_check
        check (action in ('insert', 'update', 'delete', 'verify', 'approve', 'status_change', 'export'))
);

comment on table public.audit_log is
    'Immutable application audit events. table_name plus record_id is a polymorphic reference, not a single ordinary foreign key.';
comment on column public.deceased.cause_of_death is
    'Administrator-only nullable field; never included in the public views.';
comment on column public.audit_log.ip_address is
    'Restricted nullable field for trusted server-side capture; not populated by this migration.';

create index area_site_id_idx on public.area (site_id);
create index sector_area_id_idx on public.sector (area_id);
create index block_sector_id_idx on public.block (sector_id);
create index lot_block_id_idx on public.lot (block_id);
create index lot_lot_owner_id_idx on public.lot (lot_owner_id);
create index burial_record_deceased_id_idx on public.burial_record (deceased_id);
create index burial_record_lot_id_idx on public.burial_record (lot_id);
create index burial_record_created_by_idx on public.burial_record (created_by);
create index burial_record_updated_by_idx on public.burial_record (updated_by);
create index photo_burial_id_idx on public.photo (burial_id);
create index photo_uploaded_by_idx on public.photo (uploaded_by);
create index photo_reviewed_by_idx on public.photo (reviewed_by);
create index map_node_site_id_idx on public.map_node (site_id);
create index map_edge_from_node_id_idx on public.map_edge (from_node_id);
create index map_edge_to_node_id_idx on public.map_edge (to_node_id);
create index audit_log_actor_account_id_idx on public.audit_log (actor_account_id);
create index audit_log_table_record_idx on public.audit_log (table_name, record_id);
create index account_created_by_idx on public.account (created_by);
create index account_approved_by_idx on public.account (approved_by);
create index account_status_idx on public.account (account_status);
create unique index burial_record_lot_order_key
    on public.burial_record (lot_id, interment_order_number)
    where interment_order_number is not null;

create index site_boundary_geom_gix on public.site using gist (boundary_geom);
create index area_boundary_geom_gix on public.area using gist (boundary_geom);
create index lot_location_geom_gix on public.lot using gist (location_geom);
create index map_node_location_geom_gix on public.map_node using gist (location_geom);
create index map_edge_path_geom_gix on public.map_edge using gist (path_geom);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
    new.updated_at = current_timestamp;
    return new;
end;
$$;

create trigger site_set_updated_at
before update on public.site
for each row execute function public.set_updated_at();

create trigger lot_set_updated_at
before update on public.lot
for each row execute function public.set_updated_at();

create trigger account_set_updated_at
before update on public.account
for each row execute function public.set_updated_at();

create trigger burial_record_set_updated_at
before update on public.burial_record
for each row execute function public.set_updated_at();

create or replace function public.is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select exists (
        select 1
        from public.account as a
        join public.role as r on r.role_id = a.role_id
        where a.account_id = auth.uid()
          and a.is_active
          and a.account_status = 'ACTIVE'
          and upper(r.role_name) = 'ADMIN'
    );
$$;

revoke all on function public.is_active_admin() from public;
grant execute on function public.is_active_admin() to authenticated;

create or replace function public.is_active_manager()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select exists (
        select 1
        from public.account as a
        join public.role as r on r.role_id = a.role_id
        where a.account_id = auth.uid()
          and a.is_active
          and a.account_status = 'ACTIVE'
          and upper(r.role_name) = 'MANAGER'
    );
$$;

revoke all on function public.is_active_manager() from public;
grant execute on function public.is_active_manager() to authenticated;

create or replace function public.is_active_admin_or_manager()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select public.is_active_admin() or public.is_active_manager();
$$;

revoke all on function public.is_active_admin_or_manager() from public;
grant execute on function public.is_active_admin_or_manager() to authenticated;

create or replace function public.audit_safe_row(p_table_name text, p_row jsonb)
returns jsonb
language sql
immutable
set search_path = pg_catalog, public, pg_temp
as $$
    select case p_table_name
        when 'lot_owner' then p_row - array[
            'first_name', 'middle_name', 'last_name', 'suffix', 'aliases',
            'address', 'representative_name', 'representative_contact',
            'representative_relation'
        ]
        when 'deceased' then p_row - 'cause_of_death'
        when 'burial_record' then p_row - array['service_provider', 'quality_notes']
        when 'account' then p_row - 'username'
        else p_row
    end;
$$;

revoke all on function public.audit_safe_row(text, jsonb) from public;

create or replace function public.write_audit_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    old_row jsonb;
    new_row jsonb;
    row_key text;
    event_action text;
    actor_id uuid;
begin
    if tg_op = 'DELETE' then
        old_row := to_jsonb(old);
    else
        new_row := to_jsonb(new);
    end if;

    row_key := case tg_table_name
        when 'site' then 'site_id'
        when 'area' then 'area_id'
        when 'sector' then 'sector_id'
        when 'block' then 'block_id'
        when 'lot_owner' then 'lot_owner_id'
        when 'lot' then 'lot_id'
        when 'deceased' then 'deceased_id'
        when 'role' then 'role_id'
        when 'account' then 'account_id'
        when 'burial_record' then 'burial_id'
        when 'photo' then 'photo_id'
        when 'map_node' then 'node_id'
        when 'map_edge' then 'edge_id'
        else null
    end;

    if tg_op = 'INSERT' then
        event_action := 'insert';
    elsif tg_op = 'DELETE' then
        event_action := 'delete';
    elsif tg_table_name = 'lot' and (
        (old_row ->> 'coordinate_status') is distinct from (new_row ->> 'coordinate_status')
        or (old_row ->> 'coordinate_verified') is distinct from (new_row ->> 'coordinate_verified')
    ) then
        event_action := 'verify';
    elsif tg_table_name in ('deceased', 'photo', 'lot') and (
        ((old_row ->> 'public_display') is distinct from (new_row ->> 'public_display')
            and new_row ->> 'public_display' = 'true')
        or ((old_row ->> 'approval_status') is distinct from (new_row ->> 'approval_status')
            and new_row ->> 'approval_status' = 'approved')
    ) then
        event_action := 'approve';
    elsif (
        tg_table_name = 'lot' and (old_row ->> 'status') is distinct from (new_row ->> 'status')
        or tg_table_name = 'burial_record' and (
            (old_row ->> 'record_status') is distinct from (new_row ->> 'record_status')
            or (old_row ->> 'interment_status') is distinct from (new_row ->> 'interment_status')
        )
        or tg_table_name = 'photo' and (old_row ->> 'approval_status') is distinct from (new_row ->> 'approval_status')
    ) then
        event_action := 'status_change';
    else
        event_action := 'update';
    end if;

    select a.account_id
      into actor_id
      from public.account as a
     where a.account_id = auth.uid();

    insert into public.audit_log (
        actor_account_id,
        action,
        table_name,
        record_id,
        old_values,
        new_values
    ) values (
        actor_id,
        event_action,
        tg_table_name,
        coalesce(new_row ->> row_key, old_row ->> row_key),
        public.audit_safe_row(tg_table_name, old_row),
        public.audit_safe_row(tg_table_name, new_row)
    );

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

revoke all on function public.write_audit_event() from public;

create trigger site_write_audit_event
after insert or update or delete on public.site
for each row execute function public.write_audit_event();
create trigger area_write_audit_event
after insert or update or delete on public.area
for each row execute function public.write_audit_event();
create trigger sector_write_audit_event
after insert or update or delete on public.sector
for each row execute function public.write_audit_event();
create trigger block_write_audit_event
after insert or update or delete on public.block
for each row execute function public.write_audit_event();
create trigger lot_owner_write_audit_event
after insert or update or delete on public.lot_owner
for each row execute function public.write_audit_event();
create trigger lot_write_audit_event
after insert or update or delete on public.lot
for each row execute function public.write_audit_event();
create trigger deceased_write_audit_event
after insert or update or delete on public.deceased
for each row execute function public.write_audit_event();
create trigger role_write_audit_event
after insert or update or delete on public.role
for each row execute function public.write_audit_event();
create trigger account_write_audit_event
after insert or update or delete on public.account
for each row execute function public.write_audit_event();
create trigger burial_record_write_audit_event
after insert or update or delete on public.burial_record
for each row execute function public.write_audit_event();
create trigger photo_write_audit_event
after insert or update or delete on public.photo
for each row execute function public.write_audit_event();
create trigger map_node_write_audit_event
after insert or update or delete on public.map_node
for each row execute function public.write_audit_event();
create trigger map_edge_write_audit_event
after insert or update or delete on public.map_edge
for each row execute function public.write_audit_event();

-- Account provisioning is intentionally function-only. Auth users must be
-- created or invited by a protected server-side Auth Admin operation first;
-- these functions only manage the corresponding public.account row.
create or replace function public.bootstrap_first_admin(
    p_account_id uuid,
    p_username text
)
returns public.account
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    admin_role_id bigint;
    new_account public.account;
begin
    select r.role_id
      into admin_role_id
      from public.role as r
     where upper(r.role_name) = 'ADMIN';

    if admin_role_id is null then
        raise exception 'ADMIN role is not configured';
    end if;

    if exists (
        select 1
        from public.account as a
        where a.role_id = admin_role_id
          and a.account_status = 'ACTIVE'
          and a.is_active
    ) then
        raise exception 'The first ADMIN has already been provisioned';
    end if;

    if not exists (select 1 from auth.users where id = p_account_id) then
        raise exception 'The Auth user must exist before account provisioning';
    end if;

    if p_username is null or btrim(p_username) = '' then
        raise exception 'A username is required';
    end if;

    insert into public.account (
        account_id,
        role_id,
        username,
        is_active,
        account_status,
        created_by,
        approved_by,
        approved_at
    ) values (
        p_account_id,
        admin_role_id,
        btrim(p_username),
        true,
        'ACTIVE',
        null,
        null,
        current_timestamp
    )
    returning * into new_account;

    return new_account;
end;
$$;

create or replace function public.admin_create_account(
    p_account_id uuid,
    p_username text,
    p_role_name text
)
returns public.account
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    target_role_id bigint;
    new_account public.account;
begin
    if not public.is_active_admin() then
        raise exception 'Only an active ADMIN may create accounts';
    end if;

    if not exists (select 1 from auth.users where id = p_account_id) then
        raise exception 'The Auth user must exist before account provisioning';
    end if;

    if p_username is null or btrim(p_username) = '' then
        raise exception 'A username is required';
    end if;

    select r.role_id
      into target_role_id
      from public.role as r
     where upper(r.role_name) = upper(p_role_name)
       and upper(r.role_name) in ('ADMIN', 'MANAGER');

    if target_role_id is null then
        raise exception 'Only ADMIN and MANAGER accounts may be provisioned';
    end if;

    insert into public.account (
        account_id,
        role_id,
        username,
        is_active,
        account_status,
        created_by
    ) values (
        p_account_id,
        target_role_id,
        btrim(p_username),
        false,
        'PENDING',
        auth.uid()
    )
    returning * into new_account;

    return new_account;
end;
$$;

create or replace function public.admin_approve_account(p_account_id uuid)
returns public.account
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    approved_account public.account;
begin
    if not public.is_active_admin() then
        raise exception 'Only an active ADMIN may approve accounts';
    end if;

    update public.account
       set approved_by = auth.uid(),
           approved_at = current_timestamp
     where account_id = p_account_id
       and account_status = 'PENDING'
       and approved_at is null
    returning * into approved_account;

    if not found then
        raise exception 'Only pending, unapproved accounts may be approved';
    end if;

    return approved_account;
end;
$$;

create or replace function public.admin_activate_account(p_account_id uuid)
returns public.account
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    activated_account public.account;
begin
    if not public.is_active_admin() then
        raise exception 'Only an active ADMIN may activate accounts';
    end if;

    update public.account
       set is_active = true,
           account_status = 'ACTIVE',
           deactivated_at = null
     where account_id = p_account_id
       and account_status = 'PENDING'
       and approved_at is not null
    returning * into activated_account;

    if not found then
        raise exception 'Only approved pending accounts may be activated';
    end if;

    return activated_account;
end;
$$;

create or replace function public.admin_deactivate_account(
    p_account_id uuid,
    p_account_status text
)
returns public.account
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    deactivated_account public.account;
begin
    if not public.is_active_admin() then
        raise exception 'Only an active ADMIN may deactivate accounts';
    end if;

    if p_account_id = auth.uid() then
        raise exception 'An ADMIN may not deactivate their own account';
    end if;

    if upper(p_account_status) not in ('SUSPENDED', 'REVOKED') then
        raise exception 'Deactivation status must be SUSPENDED or REVOKED';
    end if;

    if exists (
        select 1
        from public.account as target
        join public.role as target_role on target_role.role_id = target.role_id
        where target.account_id = p_account_id
          and upper(target_role.role_name) = 'ADMIN'
          and (
              select count(*)
              from public.account as active_admin
              join public.role as active_admin_role on active_admin_role.role_id = active_admin.role_id
              where active_admin.account_status = 'ACTIVE'
                and active_admin.is_active
                and upper(active_admin_role.role_name) = 'ADMIN'
          ) <= 1
    ) then
        raise exception 'The last active ADMIN may not be deactivated';
    end if;

    update public.account
       set is_active = false,
           account_status = upper(p_account_status),
           deactivated_at = current_timestamp
     where account_id = p_account_id
       and account_status = 'ACTIVE'
    returning * into deactivated_account;

    if not found then
        raise exception 'Only active accounts may be deactivated';
    end if;

    return deactivated_account;
end;
$$;

create or replace function public.admin_change_account_role(
    p_account_id uuid,
    p_role_name text
)
returns public.account
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    target_role_id bigint;
    changed_account public.account;
begin
    if not public.is_active_admin() then
        raise exception 'Only an active ADMIN may change account roles';
    end if;

    select r.role_id
      into target_role_id
      from public.role as r
     where upper(r.role_name) = upper(p_role_name)
       and upper(r.role_name) in ('ADMIN', 'MANAGER');

    if target_role_id is null then
        raise exception 'Only ADMIN and MANAGER roles may be assigned';
    end if;

    if exists (
        select 1
        from public.account as target
        join public.role as target_role on target_role.role_id = target.role_id
        where target.account_id = p_account_id
          and upper(target_role.role_name) = 'ADMIN'
          and target_role_id <> target.role_id
          and (
              select count(*)
              from public.account as active_admin
              join public.role as active_admin_role on active_admin_role.role_id = active_admin.role_id
              where active_admin.account_status = 'ACTIVE'
                and active_admin.is_active
                and upper(active_admin_role.role_name) = 'ADMIN'
          ) <= 1
    ) then
        raise exception 'The last active ADMIN may not be demoted';
    end if;

    update public.account
       set role_id = target_role_id
     where account_id = p_account_id
       and account_status <> 'REVOKED'
    returning * into changed_account;

    if not found then
        raise exception 'The target account does not exist or is revoked';
    end if;

    return changed_account;
end;
$$;

create or replace function public.export_audit_log(
    p_from timestamptz default null,
    p_to timestamptz default null
)
returns setof public.audit_log
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    actor_id uuid;
begin
    if not public.is_active_admin_or_manager() then
        raise exception 'Only active ADMIN or MANAGER accounts may export audit logs';
    end if;

    select a.account_id
      into actor_id
      from public.account as a
     where a.account_id = auth.uid();

    insert into public.audit_log (
        actor_account_id,
        action,
        table_name,
        record_id,
        old_values,
        new_values
    ) values (
        actor_id,
        'export',
        'audit_log',
        'export',
        null,
        null
    );

    return query
    select al.*
      from public.audit_log as al
     where (p_from is null or al.created_at >= p_from)
       and (p_to is null or al.created_at < p_to)
     order by al.created_at, al.audit_id;
end;
$$;

revoke all on function public.bootstrap_first_admin(uuid, text) from public;
revoke all on function public.admin_create_account(uuid, text, text) from public;
revoke all on function public.admin_approve_account(uuid) from public;
revoke all on function public.admin_activate_account(uuid) from public;
revoke all on function public.admin_deactivate_account(uuid, text) from public;
revoke all on function public.admin_change_account_role(uuid, text) from public;
revoke all on function public.export_audit_log(timestamptz, timestamptz) from public;
grant execute on function public.bootstrap_first_admin(uuid, text) to service_role;
grant execute on function public.admin_create_account(uuid, text, text) to authenticated;
grant execute on function public.admin_approve_account(uuid) to authenticated;
grant execute on function public.admin_activate_account(uuid) to authenticated;
grant execute on function public.admin_deactivate_account(uuid, text) to authenticated;
grant execute on function public.admin_change_account_role(uuid, text) to authenticated;
grant execute on function public.export_audit_log(timestamptz, timestamptz) to authenticated;

-- Base tables are not exposed to anonymous visitors. Operational tables are
-- available only to active ADMIN and MANAGER accounts through RLS. Account and
-- role mutations are function-only so account lifecycle rules cannot be bypassed.
revoke all on table
    public.site,
    public.area,
    public.sector,
    public.block,
    public.lot_owner,
    public.lot,
    public.deceased,
    public.role,
    public.account,
    public.burial_record,
    public.photo,
    public.map_node,
    public.map_edge,
    public.audit_log
from public, anon;

grant select, insert, update, delete on table
    public.site,
    public.area,
    public.sector,
    public.block,
    public.lot_owner,
    public.lot,
    public.deceased,
    public.role,
    public.account,
    public.burial_record,
    public.photo,
    public.map_node,
    public.map_edge
to authenticated;
revoke insert, update, delete on table public.role, public.account from authenticated;
grant select on table public.role, public.account to authenticated;
grant select on table public.audit_log to authenticated;

grant usage, select on sequence
    public.site_site_id_seq,
    public.area_area_id_seq,
    public.sector_sector_id_seq,
    public.block_block_id_seq,
    public.lot_owner_lot_owner_id_seq,
    public.lot_lot_id_seq,
    public.deceased_deceased_id_seq,
    public.burial_record_burial_id_seq,
    public.photo_photo_id_seq,
    public.map_node_node_id_seq,
    public.map_edge_edge_id_seq
to authenticated;

alter table public.site enable row level security;
alter table public.area enable row level security;
alter table public.sector enable row level security;
alter table public.block enable row level security;
alter table public.lot_owner enable row level security;
alter table public.lot enable row level security;
alter table public.deceased enable row level security;
alter table public.role enable row level security;
alter table public.account enable row level security;
alter table public.burial_record enable row level security;
alter table public.photo enable row level security;
alter table public.map_node enable row level security;
alter table public.map_edge enable row level security;
alter table public.audit_log enable row level security;

create policy site_admin_manager_all on public.site
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy area_admin_manager_all on public.area
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy sector_admin_manager_all on public.sector
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy block_admin_manager_all on public.block
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy lot_owner_admin_manager_all on public.lot_owner
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy lot_admin_manager_all on public.lot
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy deceased_admin_manager_all on public.deceased
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy role_admin_read on public.role
for select to authenticated
using (public.is_active_admin())
;
create policy account_admin_read on public.account
for select to authenticated
using (public.is_active_admin())
;
create policy burial_record_admin_manager_all on public.burial_record
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy photo_admin_manager_all on public.photo
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy map_node_admin_manager_all on public.map_node
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy map_edge_admin_manager_all on public.map_edge
for all to authenticated
using (public.is_active_admin_or_manager())
with check (public.is_active_admin_or_manager());
create policy audit_log_admin_manager_read on public.audit_log
for select to authenticated
using (public.is_active_admin_or_manager());

-- SECURITY DEFINER is deliberate: the view exposes only the approved columns
-- below, while direct access to all base-table columns remains denied to anon.
create or replace view public.public_burial_records
with (security_barrier = true)
as
select
    br.burial_id,
    d.display_name,
    d.birth_date,
    d.death_date,
    br.record_status,
    l.lot_code,
    l.location_geom,
    l.px_loc_x,
    l.px_loc_y,
    l.coordinate_verified as location_verified
from public.burial_record as br
join public.deceased as d on d.deceased_id = br.deceased_id
join public.lot as l on l.lot_id = br.lot_id
where br.record_status = 'active'
  and d.public_display;

create or replace view public.public_burial_photos
with (security_barrier = true)
as
select
    p.photo_id,
    p.burial_id,
    p.storage_path,
    p.file_name,
    p.caption,
    p.captured_at
from public.photo as p
join public.burial_record as br on br.burial_id = p.burial_id
join public.deceased as d on d.deceased_id = br.deceased_id
where p.approval_status = 'approved'
  and p.public_display
  and br.record_status = 'active'
  and d.public_display;

revoke all on public.public_burial_records, public.public_burial_photos from public;
grant select on public.public_burial_records, public.public_burial_photos to anon, authenticated;

comment on view public.public_burial_records is
    'Safe public surface containing only active approved burial fields; existing coordinates are visible regardless of verification status.';
comment on view public.public_burial_photos is
    'Safe public surface containing only approved public photo metadata; configure Storage policies separately.';
